### ISSUE TITLE
Strip binaries

### ISSUE THREAD

**Issue by pothos** [pothos/rust-userland#1]
The size of `nsh` and other binaries can be reduced from ~26 MB to 2 MB by stripping debug symbols

**Comment by darleybarreto** [comment]
You are using `strip` from command line, what do you think about using [`-C strip=symbols`](https://doc.rust-lang.org/rustc/codegen-options/index.html#strip) instead? There's also [sstrip](https://github.com/aunali1/super-strip), but I have never used it.

**Comment by pothos** [comment]
Thanks, makes sense to try if this is as good as using strip.
